### ISSUE TITLE
Allow overriding Name of the plugin via configuration 

### ISSUE THREAD

**Issue by msajid** [SeanFeldman/ServiceBus.CompressionPlugin#12]
It is not possible to use the same ClientEntity for registering multiple plugins in your current implementation. 

Do you see any issue in making the Name property configurable?   
` public override string Name => nameof(CompressionPlugin);`

Making the Name property configurable will help in scenarios where users need to register multiple instances of CompressionPlugin as follows 
```
  receiver.RegisterCompressionPlugin(receiverConfiguration1);
  receiver.RegisterCompressionPlugin(receiverConfiguration2);
```

**Comment by SeanFeldman** [comment]
If understood correctly, the issue is with receiving messages compressed with using methods. In addition to the original issue #9, there's also #11. To sum those up:

- Transitioning from one compression to another. (#9)
- Receiving differently compressed messages. Senders on different compression methods send to the same receiver that needs to be able to process all messages. (#11)

Compression plugin is the same plugin. What's changing is decompression method, which needs to support one or more algorithms. Re-registering the same plugin with different names feels off. I'd rather see a configuration option that allows registering multiple decompression methods.

Let me think about it and raise a PR to see what it could look like.

**Comment by SeanFeldman** [comment]
PR #13 should remove the need in this hack.
